name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: v3.13.3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Generate index.html
        run: |
          go install github.com/halkeye/helm-repo-html@v0.2.1
          /home/runner/go/bin/helm-repo-html

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update index.html"